git Tuấn Anh@DESKTOP-V9FOCQ2 MINGW64 /c/project/Jewelry (master) $ git clone fatal: You must specify a repository to clone.
usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    --reject-shallow      don't clone shallow repository
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recurse-submodules[=<pathspec>]
                          initialize submodules in the clone
    --recursive ...       alias of --recurse-submodules
    -j, --jobs <n>        number of submodules cloned in parallel
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    --reference-if-able <repo>
                          reference repository
    --dissociate          use --reference only while cloning
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --shallow-since <time>
                          create a shallow clone since a specific time
    --shallow-exclude <revision>
                          deepen history of shallow clone, excluding rev
    --single-branch       clone only one branch, HEAD or --branch
    --no-tags             don't clone any tags, and make later fetches not to follow them
    --shallow-submodules  any cloned submodules will be shallow
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository
    --server-option <server-specific>
                          option to transmit
    -4, --ipv4            use IPv4 addresses only
    -6, --ipv6            use IPv6 addresses only
    --filter <args>       object filtering
    --also-filter-submodules
                          apply partial clone filters to submodules
    --remote-submodules   any cloned submodules will use their remote-tracking branch
    --sparse              initialize sparse-checkout file to include only files at root

Tuấn Anh@DESKTOP-V9FOCQ2 MINGW64 /c/project/Jewelry (master)
$ git pull
remote: Enumerating objects: 142, done.
remote: Counting objects: 100% (142/142), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 102 (delta 78), reused 78 (delta 55), pack-reused 0
Receiving objects: 100% (102/102), 61.50 KiB | 1.86 MiB/s, done.
Resolving deltas: 100% (78/78), completed with 35 local objects.
From https://github.com/TuanAnh42/Jewelry
   c01013e..4409890  master     -> origin/master
error: Your local changes to the following files would be overwritten by merge:
        .vs/Project3/v17/.suo
Please commit your changes or stash them before you merge.
Aborting
Updating c01013e..4409890

Tuấn Anh@DESKTOP-V9FOCQ2 MINGW64 /c/project/Jewelry (master)
$ git add .

Tuấn Anh@DESKTOP-V9FOCQ2 MINGW64 /c/project/Jewelry (master)
$ git commitIncomplete
git: 'commitIncomplete' is not a git command. See 'git --help'.

Tuấn Anh@DESKTOP-V9FOCQ2 MINGW64 /c/project/Jewelry (master)
$ git commit -m